# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomClass' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod "TPKeyboardAvoiding" #scrolling behaviour when keyboard is open
  # Pods for CustomClass

end
